### ISSUE TITLE
Username and password required to connect to nuget.telerik.com

### ISSUE THREAD

**Issue by wangzhi-China** [telerik/fiddler-core-demos#1]

**Comment by lini** [comment]
To access the FiddlerCore packages from the private Nuget server, first you must have a valid Telerik account and configure it in Visual Studio - https://docs.telerik.com/reporting/using-reports-in-applications/how-to-add-the-telerik-private-nuget-feed-to-visual-studio

Alternatively, you can try FiddlerCore by downloading the library directly from Telerik's website - https://www.telerik.com/try/fiddlercore
